### ISSUE TITLE
Gulp dist does not create a distro

### ISSUE THREAD

**Issue by PaulDuvall** [stelligent/dromedary#23]
Using the current README, receive this error when running `gulp dist`: 

```
[20:47:01] 'dist:berks-vendor' errored after 9.17 ms
[20:47:01] Error: Command failed: /bin/sh: berks: command not found

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
[20:47:01] 'dist' errored after 590 ms
[20:47:01] Error in plugin 'run-sequence'
Message:
    An error occured in task 'dist:berks-vendor'.```

**Comment by jsywulak** [comment]
Looks like berkshelf isn't installed. It comes with the [Chef DK](https://downloads.chef.io/chef-dk/), so you can install that to get berks, or you can just do `gem install berks` if you have ruby installed already.

Another thing is to make sure `npm install` has been run before you start doing anything. Unlike ruby, which will error out and tell you to run bundler, node just says it's missing a specific library.

**Comment by PaulDuvall** [comment]
Need to update the instructions to describe this in more detail (and perhaps run [installchefdk.sh](https://github.com/stelligent/stelligent_commons/blob/master/chefdk/installchefdk.sh) )
